git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
matrix:
  fast_finish: true
language: node_js
node_js:
- '7'
dist: trusty
notifications:
  email:
  - ashkan@binary.com
  - apoorv@binary.com
  - amin@binary.com
branches:
  only:
  - master
  - development
before_install:
- yarn
install:
- yarn build-all
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: mvhv8Bw6Vh9IMWvgS5KrWzzGFDCaFs7Mydb79S+uuEhEUiM3mH0anLQi90ZXaTCn7iOWCDO8K/ZvSdVN+49OSQoGwli+CGX0de08jPozpn/B4C+pcTISE+RmD0D0czTVDBLBvj0HGxCvB3d9GiyjeRG2TUb5ZFPwzCooDRx3ulxQNmp3WlTsk60f660F02POTeQinJxMKtHFYt1B4i5abUUpHYNrLyTxnJQEOFu/hRPXT/wlybTTLPDRXV1W44pyH6T2Xfw10mcM5Lsg4CYIrA13SR5kmPvzVfpkDhv05qIaNt5ZWdKbN2QNTmooGmWtqjt+Lsz+Ow4xNLeufDSlBeMJLVuer+IgKg/jBJ4aBxQU4Vn8LV2u2AenOploY2BjSF7sbLC3loYbcEPMRGIS+DF/nBhi2ElctKvmg0v0w24OXr2HULgmzNhXzhSiwJ4nTLY/rnbxkwqs4XogR1K4Bbzx+rQYcEPkgOaFf1va3ScktMVcSgh0MFa7DyJvz4D8QPQxElwkwN0Bues2JYny7oznYsx0/olQY7/LHb0p4TepvUU9HQnAzKa1mrCLvf5vYxLzOL0ytwLHkFPGKaTBu0KP7cW27xgiletEdxl+2b+4mN49DmDM2zilgFmfXmUOsWC54YvgQ9GLPWjF1cI8KgcwCC0FbhqivL7AYAyFZA0=
  - secure: NbMR6KXIq4EeKEG7xSGUYgQTHc4enq1AVtIM4iNbwLTofUEKvnWAkYzkontfzu2/XiPxg5rKr2rJh3ZcSybrPV+gyKu/DuCEU1bHIVywaO2p+eSvV0XDvrMLuFqOEDNJXiMVg/l80xLUIHhCwhTVUqJz85mgOqm610pZRE0rotWmLwr21S2F57tSx6F+TK0uEN/xSr8mbCM+zcLg5vZ8+CjF87ZLZRP8yPejPOT+7hBJ0LinAUdsEN8wpY4lOL2bmEVUYgFjIeZC/OZ8xxTbOSFi9QcaRgDMxSsZ6ejdafUXlrVheCb+kVEF1f2WAAMHFlJfP5zyh86U7spnvaerfT8Nv2gjEJvb6JKVN7fU4emJGiELxDK3MGTMlOmNRdmdkqqoEmzZ/R8pzjf2yOLJ7NDNxRlnubM8SwW2KtToF6nJZ6kHjr5hCQsYpdf33DIfqSgWpDSQ7RK80Shvzi9BDH2RzV9SHM88JEbUu0W1pzftFCvFq1zEhVs1HQKnNpJKBWpp0/cNe6vwB8e7s5nxhC1Oupkpz3kRc41JJA5bUqlnC99w68KvyB/4wrk0+2pnFjvNEhfWhXJsNgK3Hwys33M4kQV3OkulnYmgrUspdymrtClOFBCARLPncAp7S2sBfRPjgAJO0NQiuz27akTEYnewrMIhedkLjhDjANBfznU=
